name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin' 
      
    # 실행 권한
    - name: Build with Gradle
      run: chmod +x gradlew  

    # 빌드
    - name: Make Directory for deliver
      run : ./gradlew clean build --exclude-task test
    
    # 디렉토리 생성
    - name: Make Directory
      run: mkdir deploy
    
    # 복사
    - name: File Copy
      run: cp ./build/libs/*.jar ./deploy/ && cp appspec.yml ./deploy/ && cp script/* ./deploy/      
     
    # 압축
    - name: Make zip file
      run: zip -r -qq -j danggeun.zip ./deploy
      
    # AWS 인증
    - name: AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ap-northeast-2

    # S3에 빌드된 파일 업로드
    - name: Upload to AWS S3
      run: aws s3 cp --region ap-northeast-2 danggeun.zip s3://danggeun2/
      
     # 코드디플로이 실행
     # aws codedeploy
    - name: Run to AWS Codedeploy
      run: aws deploy create-deployment --application-name danggeun-deploy --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name danggeun-deploy-group --s3-location bucket=danggeun2,bundleType=zip,key=danggeun.zip
